# Generated by Django 4.0.3 on 2022-09-08 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.documentaire')),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.episode')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.film')),
                ('music', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
