# Generated by Django 4.0.3 on 2022-09-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_documentaire_likes_episode_likes_film_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
