# Generated by Django 4.0.3 on 2022-09-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_alter_comment_documentaire_alter_comment_episode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='documentaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentsDocumentaire', to='video.documentaire'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentEpisode', to='video.episode'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentsFilm', to='video.film'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='music',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentsMusic', to='video.music'),
        ),
    ]
