# Generated by Django 4.0.3 on 2022-09-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_alter_comment_documentaire_alter_comment_episode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('documentaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ViewDocumentaire', to='video.documentaire')),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ViewEpisode', to='video.episode')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ViewFilm', to='video.film')),
                ('music', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ViewMusic', to='video.music')),
            ],
        ),
    ]
