# Generated by Django 4.0.3 on 2022-09-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaire',
            name='view_count',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='view_count',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='view_count',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='view_count',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
