# Generated by Django 4.0.3 on 2022-09-15 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_alter_documentaire_view_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaire',
            name='view_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='episode',
            name='view_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='film',
            name='view_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='music',
            name='view_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.DeleteModel(
            name='ViewCount',
        ),
    ]
