# Generated by Django 4.0.3 on 2022-09-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_alter_documentaire_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlater',
            name='type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
