# Generated by Django 4.0.3 on 2022-09-21 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0017_alter_documentaire_likes_alter_episode_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaire',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='episode',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='film',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='music',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentaire',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='episode',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='film',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='music',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
