# Generated by Django 4.0.3 on 2022-09-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0020_remove_profile_bio_profile_téléphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Téléphone',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
