# Generated by Django 4.0.3 on 2022-09-26 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0022_profile_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ville',
            field=models.CharField(choices=[('Nouakchott ', 'Nouakchott '), ('Trarza  ', 'Trarza  '), ('Hodh_Chargui', 'Hodh_Chargui'), ('Gorgol ', 'Gorgol '), ('Assaba ', 'Assaba '), ('Brakna  ', 'Brakna  '), ('Hodh_Gharbi  ', 'Hodh_Gharbi '), ('Guidimaka  ', 'Guidimaka  '), ('Nouadhibou ', 'Nouadhibou '), ('Adrar ', 'Adrar '), ('Zouérate', 'Zouérate'), ('Inchiri ', 'Inchiri ')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('documentaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewDocumentaire', to='video.documentaire')),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewEpisode', to='video.episode')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewFilm', to='video.film')),
                ('music', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewMusic', to='video.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
