# Generated by Django 4.0.3 on 2022-09-26 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0024_rating_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField()),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('documentaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewDocumentaire', to='video.documentaire')),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewEpisode', to='video.episode')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewFilm', to='video.film')),
                ('music', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewMusic', to='video.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
