# Generated by Django 4.0.3 on 2022-09-27 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0025_reviewrating_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='documentaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewDocumentaire', to='video.documentaire'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewEpisode', to='video.episode'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewFilm', to='video.film'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewMusic', to='video.music'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
