# Generated by Django 4.0.3 on 2022-09-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0026_alter_reviewrating_documentaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
    ]
