# Generated by Django 4.0.3 on 2022-09-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0027_alter_reviewrating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaire',
            name='description',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='description',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentsEpisode', to='video.episode'),
        ),
    ]
