# Generated by Django 4.0.3 on 2022-10-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0028_documentaire_description_episode_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commenter',
        ),
    ]
