# Generated by Django 4.0.3 on 2022-10-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0029_remove_comment_commenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
