# Generated by Django 4.0.3 on 2023-08-28 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0032_comment_commenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaire',
            name='metteurscene',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='metteurscene',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='metteurscene',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='metteurscene',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='HistoriqueVisionnage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visionage', models.DateField(null=True)),
                ('duree', models.CharField(max_length=50, null=True)),
                ('documentaires', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.documentaire')),
                ('episodes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.episode')),
                ('films', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.film')),
                ('musics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, null=True)),
                ('documentaires', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.documentaire')),
                ('episodes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.episode')),
                ('films', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.film')),
                ('musics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
