# Generated by Django 4.0.3 on 2023-09-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0032_comment_commenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentaire',
            old_name='date_création',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='date_création',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='date_création',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='date_création',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Téléphone',
            new_name='Telephone',
        ),
        migrations.AlterField(
            model_name='documentaire',
            name='type',
            field=models.CharField(choices=[('serie', 'Serie'), ('documentaire', 'Documentaire'), ('film', 'Film'), ('music', 'Music')], default='serie', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentaire',
            name='vdeo',
            field=models.FileField(null=True, upload_to='video/%y', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='type',
            field=models.CharField(choices=[('serie', 'Serie'), ('documentaire', 'Documentaire'), ('film', 'Film'), ('music', 'Music')], default='serie', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='vdeo',
            field=models.FileField(null=True, upload_to='video/%y', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedie', 'comedie'), ('histoire', 'Histoire'), ('drame', 'Drame'), ('aventure', 'aventure')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='type',
            field=models.CharField(choices=[('serie', 'Serie'), ('documentaire', 'Documentaire'), ('film', 'Film'), ('music', 'Music')], default='serie', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='vdeo',
            field=models.FileField(null=True, upload_to='video/%y', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='music',
            name='type',
            field=models.CharField(choices=[('serie', 'Serie'), ('documentaire', 'Documentaire'), ('film', 'Film'), ('music', 'Music')], default='serie', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='vdeo',
            field=models.FileField(null=True, upload_to='video/%y', verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ville',
            field=models.CharField(choices=[('Nouakchott ', 'Nouakchott '), ('Trarza  ', 'Trarza  '), ('Hodh_Chargui', 'Hodh_Chargui'), ('Gorgol ', 'Gorgol '), ('Assaba ', 'Assaba '), ('Brakna  ', 'Brakna  '), ('Hodh_Gharbi  ', 'Hodh_Gharbi '), ('Guidimaka  ', 'Guidimaka  '), ('Nouadhibou ', 'Nouadhibou '), ('Adrar ', 'Adrar '), ('Zouerate', 'Zouerate'), ('Inchiri ', 'Inchiri ')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedie', 'comedie'), ('histoire', 'Histoire'), ('drame', 'Drame'), ('aventure', 'aventure')], max_length=200, null=True),
        ),
    ]
