# Generated by Django 4.0.3 on 2023-09-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0033_documentaire_metteurscene_episode_metteurscene_and_more'),
        ('video', '0033_rename_date_création_documentaire_date_creation_and_more'),
    ]

    operations = [
    ]
